- name: get the hosted zones
  route53_facts:
    query: hosted_zone
  register: hosted_zones

- set_fact: "tld_hosted_zone_id={{ item.Id }}"
  when: item.Name == (dns_tld + '.')
  with_items: "{{ hosted_zones.HostedZones }}"

- set_fact: "provisioned_hosted_zone_id={{ item.Id }}"
  when: item.Name == (provision_id + '.' + dns_tld + '.')
  with_items: "{{ hosted_zones.HostedZones }}"

- name: get tld hosted zone records
  route53_facts:
    query: record_sets
    hosted_zone_id: "{{ tld_hosted_zone_id }}"
  register: tld_records
  
- name: get provisioned hosted zone records
  route53_facts:
    query: record_sets
    hosted_zone_id: "{{ provisioned_hosted_zone_id }}"
  register: provisioned_records
  when: provisioned_hosted_zone_id is defined

- name: delete tld record for provisioned hosted zone
  route53:
    command: delete
    zone: "{{ dns_tld }}"
    type: NS
    ttl: "{{ item.TTL | default(omit) }}"
    record: "{{ item.Name }}"
    value: "{{ item.ResourceRecords | map(attribute='Value') | join(',') }}"
  with_items: "{{ tld_records.ResourceRecordSets | selectattr('Name', 'match', provision_id + '.' + dns_tld + '.') | list }}"

- name: delete all records for provisioned hosted zone
  route53:
    command: delete
    zone: "{{ provision_id }}.{{ dns_tld }}"
    type: "{{ item.Type }}"
    ttl: "{{ item.TTL | default(omit) }}"
    record: "{{ item.Name | regex_replace('\\\\052', '*') }}"
    value: "{{ item.ResourceRecords | map(attribute='Value') | join(',') }}"
  with_items: "{{ provisioned_records.ResourceRecordSets | default([]) | rejectattr('Type', 'match', 'NS') | rejectattr('Type', 'match', 'SOA') | selectattr('AliasTarget', 'undefined') | list }}"

- name: delete all alias records for provisioned hosted zone
  route53:
    command: delete 
    zone: "{{ provision_id }}.{{ dns_tld }}"
    type: "{{ item.Type }}"
    ttl: "{{ item.TTL | default(omit) }}"
    record: "{{ item.Name | regex_replace('\\\\052', '*') }}"
    value: "{{ item.AliasTarget.DNSName }}"
    alias: yes
    alias_hosted_zone_id: "{{ item.AliasTarget.HostedZoneId }}"
  with_items: "{{ provisioned_records.ResourceRecordSets | default([]) | rejectattr('Type', 'match', 'NS') | rejectattr('Type', 'match', 'SOA') | rejectattr('AliasTarget', 'undefined') | list }}"

- name: destroy provisioned hosted zone
  route53_zone: 
    zone: "{{ provision_id }}.{{ dns_tld }}"
    state: absent